server.port: 8846
camel:
  threadpool:
    default:
      coreSize: 10
      maximumSize: 25
      maxQueueSize: 250
hystrix:
  threadpool:
    account:
      coreSize: 100
      maximumSize: 250
      maxQueueSize: 15
  group:
    default:
      circuitBreakerEnabled: true
      errorThresholdPercentage: 50
      circuitBreakerForceOpen: false
      requestVolumeThreshold: 20
      sleepWindow: 5000
      corePoolSize: 10
      executionTimeoutEnabled: true
      executionTimeout: 3000
      maximumSize: 10
      maxQueueSize: -1
      rollingStatisticalWindow: 10000
      rollingStatisticalWindowBuckets: 10
      queueSizeRejectionThreshold: 5
    account:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
      metrics:
        rollingStats:
          timeInMilliseconds: 15000
      circuitBreaker:
        enabled: true
        forceOpen: false
        forceClosed: false
        requestVolumeThreshold: 20
        errorThresholdPercentage: 50
  command:
    GetAccountById:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
        metrics:
          rollingStats:
            timeInMilliseconds: 15000
      circuitBreaker:
        enabled: true
        forceOpen: false
        forceClosed: false
        requestVolumeThreshold: 20
        errorThresholdPercentage: 50

