#Used for all profiles

#zuul section
zuul:
  routes:
    marakogr-client:
      serviceId: marakogr-client

#actuator section
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    routes:
      enabled: true

#spring section
spring:

#spring cloud
  cloud:
    config:
      fail-fast: true

server.port: 8082
