#Used for all profiles

#spring section
spring:

#spring cloud
  cloud:
    config:
      fail-fast: true

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

test: hello

server.port: 8085

#'docker' profile only
---

#spring section
spring:
  profiles:
    active: docker
  application:
    name: marakogr-client

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka/
