server:
  port: 8082

spring:
  cloud:
    config:
      fail-fast: true

zuul:
  routes:
    marakogr-client:
      serviceId: marakogr-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    routes:
      enabled: true
