#Used for all profiles

#spring section
spring:

#spring cloud
  cloud:
    config:
      fail-fast: true

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

test: hello

server.port: 8085
