#Used for all profiles

#eureka section
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server.port: 8761

#spring section
spring:
  cloud:
    config:
      fail-fast: true

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
