#Used for all profiles
kafka:
  bootstrap-servers: cjm-kafka-1.netcracker.com:9092
topic: cjm-o2uk-project-r3-4-mc-updates-sink

#spring section
spring:

#spring cloud
  cloud:
    config:
      fail-fast: true

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

test: hello

server.port: 8085

#'docker' profile only
---

#spring section
spring:
  profiles:
    active: docker
  application:
    name: marakogr-client

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
