 #Docker
---
spring:
  profiles:
    active: docker
  application:
    name: marakogr-eureka
  cloud:
    config:
      discovery:
        enabled: false
      uri: http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
      fail-fast: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
